//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MenusApp.iOS.service {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IMenuAppService", Namespace="http://tempuri.org/")]
    public partial class MenuAppService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetSectionJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetResourcesForSectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetResourceSourcesForSectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMediaStreamOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MenuAppService() {
            this.Url = "http://mobilecmssvc.tulalipdata.net/MenuAppService.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetSectionJSONCompletedEventHandler GetSectionJSONCompleted;
        
        /// <remarks/>
        public event GetResourcesForSectionCompletedEventHandler GetResourcesForSectionCompleted;
        
        /// <remarks/>
        public event GetResourceSourcesForSectionCompletedEventHandler GetResourceSourcesForSectionCompleted;
        
        /// <remarks/>
        public event GetMediaStreamCompletedEventHandler GetMediaStreamCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMenuAppService/GetSectionJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetSectionJSON(System.DateTime CurrentDate, [System.Xml.Serialization.XmlIgnoreAttribute()] bool CurrentDateSpecified, int ApplicationId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool ApplicationIdSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string webpageName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string SectionName) {
            object[] results = this.Invoke("GetSectionJSON", new object[] {
                        CurrentDate,
                        CurrentDateSpecified,
                        ApplicationId,
                        ApplicationIdSpecified,
                        webpageName,
                        SectionName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSectionJSONAsync(System.DateTime CurrentDate, bool CurrentDateSpecified, int ApplicationId, bool ApplicationIdSpecified, string webpageName, string SectionName) {
            this.GetSectionJSONAsync(CurrentDate, CurrentDateSpecified, ApplicationId, ApplicationIdSpecified, webpageName, SectionName, null);
        }
        
        /// <remarks/>
        public void GetSectionJSONAsync(System.DateTime CurrentDate, bool CurrentDateSpecified, int ApplicationId, bool ApplicationIdSpecified, string webpageName, string SectionName, object userState) {
            if ((this.GetSectionJSONOperationCompleted == null)) {
                this.GetSectionJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSectionJSONOperationCompleted);
            }
            this.InvokeAsync("GetSectionJSON", new object[] {
                        CurrentDate,
                        CurrentDateSpecified,
                        ApplicationId,
                        ApplicationIdSpecified,
                        webpageName,
                        SectionName}, this.GetSectionJSONOperationCompleted, userState);
        }
        
        private void OnGetSectionJSONOperationCompleted(object arg) {
            if ((this.GetSectionJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSectionJSONCompleted(this, new GetSectionJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMenuAppService/GetResourcesForSection", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Tds.CMS.DataObjects")]
        public Resource[] GetResourcesForSection(System.DateTime CurrentDate, [System.Xml.Serialization.XmlIgnoreAttribute()] bool CurrentDateSpecified, int ApplicationId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool ApplicationIdSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string webpageName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sectionName) {
            object[] results = this.Invoke("GetResourcesForSection", new object[] {
                        CurrentDate,
                        CurrentDateSpecified,
                        ApplicationId,
                        ApplicationIdSpecified,
                        webpageName,
                        sectionName});
            return ((Resource[])(results[0]));
        }
        
        /// <remarks/>
        public void GetResourcesForSectionAsync(System.DateTime CurrentDate, bool CurrentDateSpecified, int ApplicationId, bool ApplicationIdSpecified, string webpageName, string sectionName) {
            this.GetResourcesForSectionAsync(CurrentDate, CurrentDateSpecified, ApplicationId, ApplicationIdSpecified, webpageName, sectionName, null);
        }
        
        /// <remarks/>
        public void GetResourcesForSectionAsync(System.DateTime CurrentDate, bool CurrentDateSpecified, int ApplicationId, bool ApplicationIdSpecified, string webpageName, string sectionName, object userState) {
            if ((this.GetResourcesForSectionOperationCompleted == null)) {
                this.GetResourcesForSectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetResourcesForSectionOperationCompleted);
            }
            this.InvokeAsync("GetResourcesForSection", new object[] {
                        CurrentDate,
                        CurrentDateSpecified,
                        ApplicationId,
                        ApplicationIdSpecified,
                        webpageName,
                        sectionName}, this.GetResourcesForSectionOperationCompleted, userState);
        }
        
        private void OnGetResourcesForSectionOperationCompleted(object arg) {
            if ((this.GetResourcesForSectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetResourcesForSectionCompleted(this, new GetResourcesForSectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMenuAppService/GetResourceSourcesForSection", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Tds.Web.Service")]
        public ResourceSource[] GetResourceSourcesForSection(System.DateTime CurrentDate, [System.Xml.Serialization.XmlIgnoreAttribute()] bool CurrentDateSpecified, int ApplicationId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool ApplicationIdSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string webpageName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sectionName) {
            object[] results = this.Invoke("GetResourceSourcesForSection", new object[] {
                        CurrentDate,
                        CurrentDateSpecified,
                        ApplicationId,
                        ApplicationIdSpecified,
                        webpageName,
                        sectionName});
            return ((ResourceSource[])(results[0]));
        }
        
        /// <remarks/>
        public void GetResourceSourcesForSectionAsync(System.DateTime CurrentDate, bool CurrentDateSpecified, int ApplicationId, bool ApplicationIdSpecified, string webpageName, string sectionName) {
            this.GetResourceSourcesForSectionAsync(CurrentDate, CurrentDateSpecified, ApplicationId, ApplicationIdSpecified, webpageName, sectionName, null);
        }
        
        /// <remarks/>
        public void GetResourceSourcesForSectionAsync(System.DateTime CurrentDate, bool CurrentDateSpecified, int ApplicationId, bool ApplicationIdSpecified, string webpageName, string sectionName, object userState) {
            if ((this.GetResourceSourcesForSectionOperationCompleted == null)) {
                this.GetResourceSourcesForSectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetResourceSourcesForSectionOperationCompleted);
            }
            this.InvokeAsync("GetResourceSourcesForSection", new object[] {
                        CurrentDate,
                        CurrentDateSpecified,
                        ApplicationId,
                        ApplicationIdSpecified,
                        webpageName,
                        sectionName}, this.GetResourceSourcesForSectionOperationCompleted, userState);
        }
        
        private void OnGetResourceSourcesForSectionOperationCompleted(object arg) {
            if ((this.GetResourceSourcesForSectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetResourceSourcesForSectionCompleted(this, new GetResourceSourcesForSectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMenuAppService/GetMediaStream", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetMediaStream([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string MediaName) {
            object[] results = this.Invoke("GetMediaStream", new object[] {
                        MediaName});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMediaStreamAsync(string MediaName) {
            this.GetMediaStreamAsync(MediaName, null);
        }
        
        /// <remarks/>
        public void GetMediaStreamAsync(string MediaName, object userState) {
            if ((this.GetMediaStreamOperationCompleted == null)) {
                this.GetMediaStreamOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMediaStreamOperationCompleted);
            }
            this.InvokeAsync("GetMediaStream", new object[] {
                        MediaName}, this.GetMediaStreamOperationCompleted, userState);
        }
        
        private void OnGetMediaStreamOperationCompleted(object arg) {
            if ((this.GetMediaStreamCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMediaStreamCompleted(this, new GetMediaStreamCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Tds.CMS.DataObjects")]
    public partial class Resource {
        
        private string additionalAttributesField;
        
        private string applicationNameField;
        
        private string childMediaMimeTypeField;
        
        private string childMediaNameField;
        
        private string childMediaTypeNameField;
        
        private System.Nullable<decimal> childSectionDisplayOrderField;
        
        private bool childSectionDisplayOrderFieldSpecified;
        
        private string childSectionNameField;
        
        private System.Nullable<int> childSectionTypeIdField;
        
        private bool childSectionTypeIdFieldSpecified;
        
        private System.Nullable<decimal> displayOrderField;
        
        private bool displayOrderFieldSpecified;
        
        private string eventNameField;
        
        private ResourceType getResourceTypeField;
        
        private bool getResourceTypeFieldSpecified;
        
        private SectionType getSectionTypeField;
        
        private bool getSectionTypeFieldSpecified;
        
        private string linkTargetTypeNameField;
        
        private string linkUrlField;
        
        private string mediaNameField;
        
        private string mediaTypeNameField;
        
        private string mimeTypeNameField;
        
        private string resourceAltField;
        
        private string resourceContentField;
        
        private string resourceNameField;
        
        private string resourceTextField;
        
        private int resourceTypeField;
        
        private bool resourceTypeFieldSpecified;
        
        private System.Nullable<decimal> sectionDisplayOrderField;
        
        private bool sectionDisplayOrderFieldSpecified;
        
        private string sectionNameField;
        
        private int sectionTypeIdField;
        
        private bool sectionTypeIdFieldSpecified;
        
        private string webPageNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AdditionalAttributes {
            get {
                return this.additionalAttributesField;
            }
            set {
                this.additionalAttributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ChildMediaMimeType {
            get {
                return this.childMediaMimeTypeField;
            }
            set {
                this.childMediaMimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ChildMediaName {
            get {
                return this.childMediaNameField;
            }
            set {
                this.childMediaNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ChildMediaTypeName {
            get {
                return this.childMediaTypeNameField;
            }
            set {
                this.childMediaTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ChildSectionDisplayOrder {
            get {
                return this.childSectionDisplayOrderField;
            }
            set {
                this.childSectionDisplayOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChildSectionDisplayOrderSpecified {
            get {
                return this.childSectionDisplayOrderFieldSpecified;
            }
            set {
                this.childSectionDisplayOrderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ChildSectionName {
            get {
                return this.childSectionNameField;
            }
            set {
                this.childSectionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ChildSectionTypeId {
            get {
                return this.childSectionTypeIdField;
            }
            set {
                this.childSectionTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChildSectionTypeIdSpecified {
            get {
                return this.childSectionTypeIdFieldSpecified;
            }
            set {
                this.childSectionTypeIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> DisplayOrder {
            get {
                return this.displayOrderField;
            }
            set {
                this.displayOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DisplayOrderSpecified {
            get {
                return this.displayOrderFieldSpecified;
            }
            set {
                this.displayOrderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EventName {
            get {
                return this.eventNameField;
            }
            set {
                this.eventNameField = value;
            }
        }
        
        /// <remarks/>
        public ResourceType GetResourceType {
            get {
                return this.getResourceTypeField;
            }
            set {
                this.getResourceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GetResourceTypeSpecified {
            get {
                return this.getResourceTypeFieldSpecified;
            }
            set {
                this.getResourceTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public SectionType GetSectionType {
            get {
                return this.getSectionTypeField;
            }
            set {
                this.getSectionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GetSectionTypeSpecified {
            get {
                return this.getSectionTypeFieldSpecified;
            }
            set {
                this.getSectionTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LinkTargetTypeName {
            get {
                return this.linkTargetTypeNameField;
            }
            set {
                this.linkTargetTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LinkUrl {
            get {
                return this.linkUrlField;
            }
            set {
                this.linkUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MediaName {
            get {
                return this.mediaNameField;
            }
            set {
                this.mediaNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MediaTypeName {
            get {
                return this.mediaTypeNameField;
            }
            set {
                this.mediaTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MimeTypeName {
            get {
                return this.mimeTypeNameField;
            }
            set {
                this.mimeTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ResourceAlt {
            get {
                return this.resourceAltField;
            }
            set {
                this.resourceAltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ResourceContent {
            get {
                return this.resourceContentField;
            }
            set {
                this.resourceContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ResourceName {
            get {
                return this.resourceNameField;
            }
            set {
                this.resourceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ResourceText {
            get {
                return this.resourceTextField;
            }
            set {
                this.resourceTextField = value;
            }
        }
        
        /// <remarks/>
        public int ResourceType {
            get {
                return this.resourceTypeField;
            }
            set {
                this.resourceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResourceTypeSpecified {
            get {
                return this.resourceTypeFieldSpecified;
            }
            set {
                this.resourceTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> SectionDisplayOrder {
            get {
                return this.sectionDisplayOrderField;
            }
            set {
                this.sectionDisplayOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SectionDisplayOrderSpecified {
            get {
                return this.sectionDisplayOrderFieldSpecified;
            }
            set {
                this.sectionDisplayOrderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SectionName {
            get {
                return this.sectionNameField;
            }
            set {
                this.sectionNameField = value;
            }
        }
        
        /// <remarks/>
        public int SectionTypeId {
            get {
                return this.sectionTypeIdField;
            }
            set {
                this.sectionTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SectionTypeIdSpecified {
            get {
                return this.sectionTypeIdFieldSpecified;
            }
            set {
                this.sectionTypeIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string WebPageName {
            get {
                return this.webPageNameField;
            }
            set {
                this.webPageNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Tds.CMS.DataObjects")]
    public enum ResourceType {
        
        /// <remarks/>
        UNKNOWN,
        
        /// <remarks/>
        MEDIA,
        
        /// <remarks/>
        TEXT,
        
        /// <remarks/>
        LINK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Tds.CMS.DataObjects")]
    public enum SectionType {
        
        /// <remarks/>
        ORCA_AMPHITHEATRE_ACTIVITY_WIDGET,
        
        /// <remarks/>
        BEDROOM_SPECIALTY_ACTIVITY_WIDGET,
        
        /// <remarks/>
        PACKAGE_SPECIALS_ACTIVITY_WIDGET,
        
        /// <remarks/>
        RESORT_SPECIALS_ACTIVITY_WIDGET,
        
        /// <remarks/>
        TSPA_ACTIVITY_WIDGET,
        
        /// <remarks/>
        FLORAL_TABS_WIDGET,
        
        /// <remarks/>
        BEDROOM_TABS_WIDGET,
        
        /// <remarks/>
        JACKPOT_INFO,
        
        /// <remarks/>
        RECIPE,
        
        /// <remarks/>
        PAGE_SLOT_LIST_CONTENT,
        
        /// <remarks/>
        FORM_SIGNUP,
        
        /// <remarks/>
        FORM_CONTACT,
        
        /// <remarks/>
        FORM_PHONE,
        
        /// <remarks/>
        DIRECTIONS,
        
        /// <remarks/>
        FORM_INFRASTRUCTURE,
        
        /// <remarks/>
        SPECIALS_PAGE_ARTICLE_CONTENT,
        
        /// <remarks/>
        INLINE_PDF_LINKTEXT,
        
        /// <remarks/>
        IMAGE_GALLERY_WIDGET,
        
        /// <remarks/>
        UNKNOWN,
        
        /// <remarks/>
        GENERAL_INFO,
        
        /// <remarks/>
        PAGE_DESCRIPTON_CONTENT,
        
        /// <remarks/>
        PAGE_ARTICLES_CONTENT,
        
        /// <remarks/>
        COPY_SECTION_CONTENT,
        
        /// <remarks/>
        OTHER,
        
        /// <remarks/>
        META_DATA,
        
        /// <remarks/>
        PAGE_IMAGE_LIST_CONTENT,
        
        /// <remarks/>
        WIDGET_CONTENT,
        
        /// <remarks/>
        EXPANDABLE_CONTENT,
        
        /// <remarks/>
        HEADER_CONTENT,
        
        /// <remarks/>
        FOOTER_CONTENT,
        
        /// <remarks/>
        ADVERTISEMENT,
        
        /// <remarks/>
        PAGE_FORM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Tds.Web.Service")]
    public partial class ResourceSource {
        
        private byte[] binaryField;
        
        private string mediaNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] Binary {
            get {
                return this.binaryField;
            }
            set {
                this.binaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MediaName {
            get {
                return this.mediaNameField;
            }
            set {
                this.mediaNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetSectionJSONCompletedEventHandler(object sender, GetSectionJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSectionJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSectionJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetResourcesForSectionCompletedEventHandler(object sender, GetResourcesForSectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetResourcesForSectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetResourcesForSectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Resource[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Resource[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetResourceSourcesForSectionCompletedEventHandler(object sender, GetResourceSourcesForSectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetResourceSourcesForSectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetResourceSourcesForSectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResourceSource[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResourceSource[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetMediaStreamCompletedEventHandler(object sender, GetMediaStreamCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMediaStreamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMediaStreamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591